version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - pip install -r requirements.txt

  build:
    commands:
      - echo Build started on `date`
      - echo Building the project...

artifacts:
  files:
    - '**/*'
